### ISSUE TITLE
[HCA DP] Create an end to end smoke test using playwright

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-data-portal#1]
- [x] Setup repo and get app running
- [x] Install playwright in the repo
- [x] Make an initial test against data.humancellatlas.org to check the HTML title element.

**Comment by MillenniumFalconMechanic** [comment]
- [ ]  Investigating best practices for tagging/locating elements in tests.
- [ ] Add test for HTML tiltle.
- [ ] Update existing counts to test via regex, something like: digits followed optional decimal point and digits followed by optional letters (you can possibly limit the letters to the set we know, see [formatter](https://github.com/DataBiosphere/data-portal/blob/main/src/utils/number-format.service.js)). See also https://regex101.com/.
- [ ] Add tests for header menu items.
- [ ] Update tests to run headed.

**Comment by MillenniumFalconMechanic** [comment]
- [ ] What is `page`?
- [ ] What is the type returned when you use `page.locator`, is it a wrapper around array, or is some kind of promise?
- [ ] Why do you need `await metricEls.count()`?
- [ ] Removed unused variables!
- [ ] Check if you can remove `await` before `expect(foo).toBar(bat)` throughout.

**Comment by MillenniumFalconMechanic** [comment]
- [ ] Create draft PR.
